# Vagrant Configure File
## onesword0618

### Requre Vagrant Version
Vagrant.require_version ">= 2.2.7"

### Vagrant configure version
#### Using "config"
Vagrant.configure("2") do |config|

##### Remote-VM
###### config.vim
  config.vim.define "remote" do |remote|
    remote.vim.box = "Ubuntu_19.10_eoan"
    remote.vim.box_check_update = false
    remote.vm.hostname = "devlopments-remote"
    remote.vm.network "private_network", ip: "172.16.97.102"
    remote.vm.synced_folder "../develop", "/vagrant_data"
    remote.vim.post_up_message = "developments environment"

    ###### provider
    remote.vim.provider "virtualbox" do |vb|
      vb.name = "developments"
      vb.memory = 6144 # 1GB = 1024MB
      vb.gui = true
      vb.cpus = 2

      ###### Virtual Box Manage
      ####### https://www.virtualbox.org/manual/ch08.html#vboxmanage-cmd-overview
      ######## modify-vm
      ######### https://www.virtualbox.org/manual/ch08.html#vboxmanage-modifyvm
      vb.customize [
        "modifyvm", :id,
        "--vram", "256", # [--vram <vramsize in MB>]
        "--clipboard", "bidirectional", # [--clipboard-mode disabled|hosttoguest|guesttohost|bidirectional]
        "--accelerate3d", "on", # [--accelerate3d on|off]
        "--hwvirtex", "on", # [--hwvirtex on|off]
        "--nestedpaging", "on", # [--nestedpaging on|off]
        "--largepages", "on", # [--largepages on|off]
        "--ioapic", "on", # [--ioapic on|off]
        "--pae", "on", # [--pae on|off]
        "--paravirtprovider", "kvm", #  [--paravirtprovider none|default|legacy|minimal|hyperv|kvm]
      ]
    end

    remote.vm.provision "shell", inline: <<-EOS
      wget -q https://www.ubuntulinux.jp/ubuntu-ja-archive-keyring.gpg -O- | sudo apt-key add -
      wget -q https://www.ubuntulinux.jp/ubuntu-jp-ppa-keyring.gpg -O- | sudo apt-key add -
      sudo wget https://www.ubuntulinux.jp/sources.list.d/bionic.list -O /etc/apt/sources.list.d/ubuntu-ja.list
      sudo apt update && sudo apt full-upgrade -y && sudo apt autoremove -y && sudo apt clean
      sudo apt install -y ubuntu-desktop ubuntu-defaults-ja aptitude curl dnsutils lsof zip unzip lsb-release tree man
      sudo timedatectl set-timezone Asia/Tokyo
      sudo update-alternatives --set editor $(update-alternatives --list editor | grep 'vim.basic')
    EOS
  end
  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"
end
